language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

os: linux

env:
  - SYMFONY_VERSION="^2.0||^3.0"
    COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY_VERSION="^2.0||^3.0"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/resources

before_install:
  - .travis-scripts/cache-browscap.sh
  - phpenv config-rm xdebug.ini || echo "xdebug was not installed"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget https://github.com/composer/composer/releases/download/1.5.2/composer.phar

install:
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - php -d memory_limit=-1 composer.phar update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS -vv

script:
  - php composer.phar validate
  - vendor/bin/phpunit --no-coverage --colors --verbose

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      env: SYMFONY_VERSION="^2.0||^3.0"
           COMPOSER_FLAGS="--prefer-lowest"
      dist: precise
    - php: 5.3
      env: SYMFONY_VERSION="^2.0||^3.0"
      dist: precise
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: 7.1
      env: SYMFONY_VERSION="~2.3.0"
    - php: 7.1
      env: SYMFONY_VERSION="~2.4.0"
    - php: 7.1
      env: SYMFONY_VERSION="~2.5.0"
    - php: 7.1
      env: SYMFONY_VERSION="~2.6.0"
    - php: 7.1
      env: SYMFONY_VERSION="~2.7.0"
    - php: 7.1
      env: SYMFONY_VERSION="^2.8.0"
    - php: 7.1
      env: SYMFONY_VERSION="~3.0.0"
    - php: 7.1
      env: SYMFONY_VERSION="~3.1.0"
    - php: 7.1
      env: SYMFONY_VERSION="~3.2.0"
    - php: 7.1
      env: SYMFONY_VERSION="^3.3.0"
    - stage: test with coverage
      php: 7.1
      env: SYMFONY_VERSION="^2.0||^3.0"
      before_install:
        - .travis-scripts/cache-browscap.sh
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - wget https://github.com/composer/composer/releases/download/1.5.2/composer.phar
      script: php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose
      after_success:
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - stage: check coding style
      php: 7.1
      env: COMPOSER_FLAGS=""
      script:
        - wget https://github.com/squizlabs/PHP_CodeSniffer/releases/download/3.1.1/phpcs.phar && php phpcs.phar --colors
        - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.7.1/php-cs-fixer.phar && php -n -d memory_limit=768M php-cs-fixer.phar fix --dry-run -vv
    - stage: static code analysis
      php: 7.1
      env: COMPOSER_FLAGS=""
      install:
        - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
        - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
        - php composer.phar require phpstan/phpstan --no-update
        - php -d memory_limit=-1 composer.phar update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --no-dev $COMPOSER_FLAGS -vv
      script: vendor/bin/phpstan analyse -l 7 -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src tests
