language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

os: linux

env:
  - SYMFONY_VERSION="^2.3||^3.0||^4.0"
    COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY_VERSION="^2.3||^3.0||^4.0"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/Resources

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug was not installed"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget https://github.com/composer/composer/releases/download/1.5.2/composer.phar

install:
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
  - php composer.phar require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - php -d memory_limit=-1 composer.phar update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS -vv

script:
  - php composer.phar validate
  - .travis-scripts/cache-browscap.sh
  - vendor/bin/phpunit --no-coverage --colors --verbose

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 5.3
      env: SYMFONY_VERSION="^2.3||^3.0||^4.0"
           COMPOSER_FLAGS="--prefer-lowest"
      dist: precise
    - php: 5.3
      env: SYMFONY_VERSION="^2.3||^3.0||^4.0"
      dist: precise
    - php: nightly
      env: SYMFONY_VERSION="^2.3||^3.0||^4.0"
           COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: 7.1
      env: SYMFONY_VERSION="~2.3.0"
    - php: 7.1
      env: SYMFONY_VERSION="~2.4.0"
    - php: 7.1
      env: SYMFONY_VERSION="~2.5.0"
    - php: 7.1
      env: SYMFONY_VERSION="~2.6.0"
    - php: 7.1
      env: SYMFONY_VERSION="~2.7.0"
    - php: 7.1
      env: SYMFONY_VERSION="^2.8.0"
    - php: 7.1
      env: SYMFONY_VERSION="~3.0.0"
    - php: 7.1
      env: SYMFONY_VERSION="~3.1.0"
    - php: 7.1
      env: SYMFONY_VERSION="~3.2.0"
    - php: 7.1
      env: SYMFONY_VERSION="^3.3.0"
    - php: 7.1
      env: SYMFONY_VERSION="~4.0.0"
    - stage: test with coverage
      php: 7.1
      env: SYMFONY_VERSION="^2.3||^3.0||^4.0"
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - wget https://github.com/composer/composer/releases/download/1.5.2/composer.phar
      script:
        - .travis-scripts/cache-browscap.sh
        - php -d browscap=$TRAVIS_BUILD_DIR/Resources/browscap.ini vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose
      after_success:
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
